### PR TITLE
Cloudflare ALIAS support

### LINKED ISSUE #91: CloudFlare issue
When trying to run octodns agains cloudflare I get the following issues 
 File "/home/ec2-user/dns/env/local/lib/python2.7/site-packages/octodns/record.py", line 115, in new
    raise ValidationError(fqdn, reasons)
octodns.record.ValidationError: Invalid record mydomain.com.
  - root CNAME not allowed

Any advice on how to fix ?

### PR DESCRIPTION
**Pull request by ross**
They're translated to/from root `CNAME` records which have the same semantics in Cloudflare as the octoDNS `ALIAS` record type.

Fixes #91
/cc @parkr @jr-RXcode

### CODE REVIEW

**Comment by parkr** [comment]
@ross On Mobile at the moment, but wanted to ask if there’s a way to try out `master` using pip? Or is cloning the repo the best option to test this new code?

**Comment by ross** [comment]
You can install a specific sha with a git url. You'll need to update setuptools first to make sure you get all the requirements, something like the following should do the trick.

```
$ virtualenv env
$ source env/bin/active
$ pip install -U pip setuptools
$ pip install -e git+https://git@github.com/github/octodns.git@master#egg=octodns
```

`master` can be replaced with commitish to get something specific.

**Comment by parkr** [comment]
@ross Great, thank you! Just gave this another try. It looks like Cloudflare is a strange ❄️ of exceptions. It allows you to set a CNAME regardless of the presence of other records. For example, I have CNAME and TXT records setup for `talk.jekyllrb.com.`. Using the latest master, I receive:

```console
~/jekyll/dns$ octodns-dump --config=./config/production.yaml --output=tmp/ jekyllrb.com. cloudflare
2018-01-07T18:58:14  [140735856747328] INFO  Manager __init__: config_file=./config/production.yaml
2018-01-07T18:58:14  [140735856747328] INFO  Manager __init__:   max_workers=1
2018-01-07T18:58:14  [140735856747328] INFO  Manager __init__:   max_workers=False
2018-01-07T18:58:14  [140735856747328] INFO  Manager dump: zone=jekyllrb.com., sources=()
Traceback (most recent call last):
  File "/Users/parkr/jekyll/dns/env/bin/octodns-dump", line 11, in <module>
    load_entry_point('octodns', 'console_scripts', 'octodns-dump')()
  File "/Users/parkr/jekyll/dns/env/src/octodns/octodns/cmds/dump.py", line 31, in main
    manager.dump(args.zone, args.output_dir, args.lenient, *args.source)
  File "/Users/parkr/jekyll/dns/env/src/octodns/octodns/manager.py", line 360, in dump
    source.populate(zone, lenient=lenient)
  File "/Users/parkr/jekyll/dns/env/src/octodns/octodns/provider/cloudflare.py", line 197, in populate
    zone.add_record(record)
  File "/Users/parkr/jekyll/dns/env/src/octodns/octodns/zone.py", line 91, in add_record
    .format(record.fqdn))
octodns.zone.InvalidNodeException: Invalid state, CNAME at talk.jekyllrb.com. cannot coexist with other records
```

octodns is doing right by users by complying with the DNS spec, but Cloudflare is all sorts of confusing for octodns. It looks like CNAME's are like ALIAS's the moment another record exists for subdomains.

**Comment by ross** [comment]
> octodns is doing right by users by complying with the DNS spec, but Cloudflare is all sorts of confusing for octodns. It looks like CNAME's are like ALIAS's the moment another record exists for subdomains.

Hrm, guess that's their work-around. There isn't currently a way to disable that validation. octoDNS's current use of ALIAS was only intended for the root record case (though in theory it might support using it elsewhere. To be honest it probably either needs tested out on the providers or else update the validation to make sure it's only used at the root.

**Pull request merged**
