### PR TITLE
Features# Geo support added for CNAME Records. ISSUE - #62

### PR DESCRIPTION
**Pull request by ashishprajapati**
@ross , I have implemented the Geo support for the cname records. Below, you can find out the example configuration snippet that will work after this update. 

```
www2:
  geo:
    AS:
      - cdn.asia.
    EU:
      - cdn.eu.
    NA-US-CA:
      - cdn.com.
  ttl: 300
  type: CNAME
  value: cdn.net.
```

Please, have a look and let me know if anything.

### CODE REVIEW

**Comment by ashishprajapati** [comment]
I am working on it for fixing it as some of the test cases are failing.

**Comment by ross** [comment]
Hi @ashishprajapati I have an existing start on geo CNAME support in https://github.com/github/octodns/tree/geo-cname, but that work got stalled and I haven't had time to get back to it. 

One thing to keep in mind is that both Dyn and Route53 have Geo so in order to add CNAME support it'd either need to be done in both of them (ideally) or things would have to be reworked so that Geo CNAME support is optional (less than ideal).

**Comment by ashishprajapati** [comment]
Hello @ross I have seen your geo work here at https://github.com/github/octodns/tree/geo-cname  . It make sense that it should be implement for Dyn and Route53 both of them in same build. I am on it and wants to proceed further with it. Is there anything you want to suggest me?

**Comment by ross** [comment]
To be honest I'm not even sure where I left that branch at. I went ahead and created a PR of it, https://github.com/github/octodns/pull/101, so we'd get CI runs etc. If I recall I think what was there was mostly working, but I wasn't super happy with how a few bits of it had turned out. I'll try and find some time to dig back into it this week and figure out the details.

**Comment by ashishprajapati** [comment]
@ross had already started worked on that and it’s open since years so I have closed it now :)

**Pull request closed without merging**
