### PR TITLE
v0.9.10 version bump and CHANGELOG update

### PR DESCRIPTION
**Pull request by ross**
## v0.9.10 - 2020-04-20 - Dynamic NS1 and lots of misc

* Added support for dynamic records to Ns1Provider, updated client and rate
  limiting implementation
* Moved CI to use GitHub Actions
* Set up dependabot to automatically PR requirements updates
* Pass at bumping all of the requirements and Dependabot them going forward
* Enhanced `dynamic` pool validation rules
* Delegation set support for Route53 and fix for CNAME/A ordering issues
* DNSimple sandbox support
* OVHProvider support for CAA
* Akamai rename FastDNS to EdgeDNS
* Transip bumped to 2.1.2 which should get away from its SOAP api which is EOLd

### CODE REVIEW

**Comment by ross** [comment]
https://pypi.org/project/octodns/0.9.10/

**Comment by brianeclow** [comment]
I am getting the following on a clean install:
```
ERROR: botocore 1.15.34 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
```
Is this expected?

**Comment by ross** [comment]
> I am getting the following on a clean install:

Can you provide steps to reproduce? I just tried a clean virtualenvs for py2 and 3 with `pip install octodns` and get successful installs of 0.9.10 in both.

**Comment by brianeclow** [comment]
I'm installing it with a `requirements.txt`:
```
pip3 install --quiet -U -r requirements.txt
```
It includes the octoDNS version and the contents of octoDNS's requirement.txt

**Comment by ross** [comment]
Hrm. I am getting a message printed when I do that, but things do seem to be successfully installing:

```
(env) $ pip install octodns -r ~/github/octodns/requirements.txt
...
ERROR: botocore 1.15.34 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
Installing collected packages: pycountry, certifi, chardet, urllib3, idna, requests, ipaddress, PyYaml, dnspython, attrs, zipp, importlib-metadata, six, pyparsing, packaging, pluggy, wcwidth, more-itertools, py, pytest, pytest-mock, pprintpp, repoze.lru, coverage, pytest-cov, wheel, pycountry-convert, python-dateutil, natsort, octodns, azure-common, isodate, oauthlib, requests-oauthlib, msrest, PyJWT, pycparser, cffi, cryptography, adal, msrestazure, azure-mgmt-dns, docutils, jmespath, botocore, s3transfer, boto3, dyn, pyasn1, pyOpenSSL, ndg-httpsclient, edgegrid-python, setuptools, pytz, protobuf, googleapis-common-protos, pyasn1-modules, rsa, cachetools, google-auth, google-api-core, google-cloud-core, google-cloud-dns, ns1-python, ovh, suds-jurko, transip
    Running setup.py install for PyYaml ... done
  Attempting uninstall: wheel
    Found existing installation: wheel 0.24.0
    Uninstalling wheel-0.24.0:
      Successfully uninstalled wheel-0.24.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 46.1.3
    Uninstalling setuptools-46.1.3:
      Successfully uninstalled setuptools-46.1.3
Successfully installed PyJWT-1.7.1 PyYaml-5.3.1 adal-1.2.2 attrs-19.3.0 azure-common-1.1.25 azure-mgmt-dns-3.0.0 boto3-1.12.34 botocore-1.15.34 cachetools-4.1.0 certifi-2020.4.5.1 cffi-1.14.0 chardet-3.0.4 coverage-5.1 cryptography-2.9.2 dnspython-1.16.0 docutils-0.16 dyn-1.8.1 edgegrid-python-1.1.1 google-api-core-1.17.0 google-auth-1.14.1 google-cloud-core-1.3.0 google-cloud-dns-0.32.0 googleapis-common-protos-1.51.0 idna-2.9 importlib-metadata-1.6.0 ipaddress-1.0.23 isodate-0.6.0 jmespath-0.9.5 more-itertools-8.2.0 msrest-0.6.13 msrestazure-0.6.3 natsort-6.2.1 ndg-httpsclient-0.5.1 ns1-python-0.15.0 oauthlib-3.1.0 octodns-0.9.10 ovh-0.5.0 packaging-20.3 pluggy-0.13.1 pprintpp-0.4.0 protobuf-3.11.3 py-1.8.1 pyOpenSSL-19.1.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycountry-19.8.18 pycountry-convert-0.7.2 pycparser-2.20 pyparsing-2.4.7 pytest-5.4.1 pytest-cov-2.8.1 pytest-mock-3.1.0 python-dateutil-2.8.1 pytz-2019.3 repoze.lru-0.7 requests-2.23.0 requests-oauthlib-1.3.0 rsa-4.0 s3transfer-0.3.3 setuptools-44.1.0 six-1.14.0 suds-jurko-0.6 transip-2.1.2 urllib3-1.25.9 wcwidth-0.1.9 wheel-0.34.2 zipp-3.1.0
(env)otter:tmp ross$ pip freeze | grep boto
boto3==1.12.34
botocore==1.15.34
(env)otter:tmp ross$ pip freeze | grep octodns
octodns==0.9.10
```

**Comment by brianeclow** [comment]
Yup, that has my results as well. I don't seem to be losing functionality, it is just annoyance.

**Pull request merged**
